//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18051
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPFriend.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPFriend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   シート「{0}」はブック「{1}」に存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Book_GetSheet {
            get {
                return ResourceManager.GetString("M_Fixture_Book_GetSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に「D.パラメタ」の記述が見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Case_GetArray {
            get {
                return ResourceManager.GetString("M_Fixture_Case_GetArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に「D.パラメタ」の記述が見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Case_GetList {
            get {
                return ResourceManager.GetString("M_Fixture_Case_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に「D.パラメタ」の記述が見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Case_GetObject {
            get {
                return ResourceManager.GetString("M_Fixture_Case_GetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セクション番号 {0} は間違っています（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Case_GetSection {
            get {
                return ResourceManager.GetString("M_Fixture_Case_GetSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に「E.取得データ」の記述が見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Case_Validate_Object {
            get {
                return ResourceManager.GetString("M_Fixture_Case_Validate_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に「F.更新後データ」の記述が見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Case_Validate_Storage {
            get {
                return ResourceManager.GetString("M_Fixture_Case_Validate_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」という名前のクラスが見つかりませんでした。テスト対象クラスのクラスが「{0}」でない場合、テストクラス名をテスト対象クラス名+&quot;Test&quot;とするか、引数で明示的にテスト対象クラス名を指定してください。({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_FixtureBook_GetDefaultTargetClass {
            get {
                return ResourceManager.GetString("M_Fixture_FixtureBook_GetDefaultTargetClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」というクラス名から、テスト対象クラス名を類推できませんでした。例えばテスト対象クラス名が  &quot;TargetClass&quot; である時、テストクラス名を &quot;TagetClassTest&quot; とすればこの例外は発生しなくなります。({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_FixtureBook_GetDefaultTargetClassName {
            get {
                return ResourceManager.GetString("M_Fixture_FixtureBook_GetDefaultTargetClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」というメソッドは「{1}」にありませんでした。別の名前のメソッドをテストしたい場合は、このメソッドの引数にテスト対象クラスとテスト対象メソッド名を明示的に指定してください。({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_FixtureBook_GetDefaultTargetMethod {
            get {
                return ResourceManager.GetString("M_Fixture_FixtureBook_GetDefaultTargetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「E.取得データ」がありません。({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_FixtureBook_GetSection_ExpectedResult {
            get {
                return ResourceManager.GetString("M_Fixture_FixtureBook_GetSection_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「D.パラメタ」がありません。({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_FixtureBook_GetSection_ObjectForExec {
            get {
                return ResourceManager.GetString("M_Fixture_FixtureBook_GetSection_ObjectForExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「E.取得データ」に{0}番目のテーブル定義がありません。({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_FixtureBook_GetTable_ExpectedResult {
            get {
                return ResourceManager.GetString("M_Fixture_FixtureBook_GetTable_ExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「D.パラメタ」に{0}番目のテーブル定義がありません。({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_FixtureBook_GetTable_ObjectForExec {
            get {
                return ResourceManager.GetString("M_Fixture_FixtureBook_GetTable_ObjectForExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル定義「{0}」は「{1}」の中に記述されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Section_GetTable {
            get {
                return ResourceManager.GetString("M_Fixture_Section_GetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テストケース 「{0}」はシート「{1}」に存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Sheet_GetCase {
            get {
                return ResourceManager.GetString("M_Fixture_Sheet_GetCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クラス ({0}) のインスタンスが作成できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Conductor_CannotCreateInstance {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Conductor_CannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クラス ({0}) には {1} というメソッドがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Conductor_CannotFindMethod {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Conductor_CannotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたインデックス ({0}) の引数はありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Conductor_InvalidParameterIndex {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Conductor_InvalidParameterIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expect / ExpectReturn / ExpectThrown が実行されていません。これらのいずれかのメソッドの実行後に {0} を呼び出してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Conductor_InvalidStatus {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Conductor_InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBテーブル「{0}」へのデータ登録に失敗しました。（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Database_CreateInsertCommand {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Database_CreateInsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {2}行目のデータを用いたDBテーブル「{0}」の行削除が失敗しました。（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Database_DeleteRow {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Database_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBテーブル「{0}」の情報取得に失敗しました。（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Database_GetMetaData {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Database_GetMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {2}行目のデータをDBテーブル「{0}」に登録できませんでした。（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_Database_InsertRow {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_Database_InsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース接続設定がありません。
        ///App.config ファイルを作成し、以下のように connectionStrings の設定を行ってください。
        ///-----------------
        ///App.config 記述例
        ///-----------------
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;connectionStrings&gt;
        ///    &lt;clear/&gt;
        ///    &lt;add name=&quot;任意の接続名&quot; providerName=&quot;プロバイダ名&quot; connectionString=&quot;接続文字列&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///&lt;/configuration&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_DatabaseConnection_NoConnectionSettings {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_DatabaseConnection_NoConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された名前（{0}）のデータベース接続設定がありません。
        ///App.config ファイルを作成し、以下のように connectionStrings の設定を行ってください。
        ///-----------------
        ///App.config 記述例
        ///-----------------
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;connectionStrings&gt;
        ///    &lt;clear/&gt;
        ///    &lt;add name=&quot;{0}&quot; providerName=&quot;プロバイダ名&quot; connectionString=&quot;接続文字列&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///&lt;/configuration&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_DatabaseConnection_NoSuchName {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_DatabaseConnection_NoSuchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBテーブル「{0}」には「{1}」という名前の列はありません。（{2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_DatabaseOperator_Column_NotFound {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_DatabaseOperator_Column_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBテーブル「{0}」には、{2}行目で指定された条件に合致するデータが見つかりません。（{1}、検索条件：{3}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_DatabaseValidator_NotFound {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_DatabaseValidator_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBテーブル「{0}」には、{2}行目で指定された条件に合致するデータが見つかりません。列名の先頭に * を付けて検索条件を指定することをおすすめします。（{1}、検索条件：{3}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_DatabaseValidator_NotFound_With_Comment {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_DatabaseValidator_NotFound_With_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBテーブル「{0}」には、{2}行目で指定された条件に合致するデータが複数件あります。一件になるような検索条件を指定してください（{1}、検索条件：{3}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_DatabaseValidator_OneMoreData {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_DatabaseValidator_OneMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBテーブル「{0}」には、削除されているはずのデータ（{2}行目）が存在します。（{1}、検索条件：{3}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_DatabaseValidator_UnexpectedData {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_DatabaseValidator_UnexpectedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {4}行目で列 {0} に指定された &quot;{1}&quot; を {2}型に変換できません。（{3}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectFactory_ConvertError {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectFactory_ConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {3}行目のデータの列名「{0}」と同じ名前のプロパティは{1}型に存在しません。（{2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectFactory_NoSuchProperty {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectFactory_NoSuchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {3}行目の列「{0}」の値 &quot;{4}&quot; を{1} に設定できません。（{2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectFactory_SetProperty {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectFactory_SetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたオブジェクトからテーブル定義を特定できませんでした。メソッドの引数で明示的にテーブル定義名を指定してください。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectOperator_GetTableName {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectOperator_GetTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1}行目で列{2}に指定された予想結果は &quot;{3}&quot; ですが、実際の値は &quot;{4}&quot; {5} でした。 （{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_AssertEquals {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_AssertEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル定義「{1}」には{2}行のデータが予想結果として定義されていますが、実際には{3}行でした。（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_AssertLineNumber {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_AssertLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル定義「{0}」が定義されていますが、実際の値は null でした。（{1}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_AssertNull {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_AssertNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「E.取得データ」のテーブル定義の数({0})が DataSet に含まれる DataTable の数({1})と異なります。DataSetの中の特定のDataTableのみを検証したい場合は、Validateメソッドの引数でテーブル定義名を明示的に指定してください。({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_AssertTableNumberEquals {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_AssertTableNumberEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引数で指定された定義名は「{0}」ですが、実際のDataSet中のDataTableは「{1}」しかありませんでした。（{2}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_AssertTableNumberExp {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_AssertTableNumberExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル定義名が明示的に指定されなかったため、DataSet の全 DataTable を検証しようとしましたが、「E.取得データ」のテーブル定義の数({0})が DataSet に含まれる DataTable の数({1})よりも少なかったため、検証できませんでした。 ({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_AssertTableNumberImp {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_AssertTableNumberImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された例外 {0} が発生しませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_Exception {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル定義名が明示的に指定されなかったため、全テーブルを順番に検証します。({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_Temp_ObjectValidator_UseTableOrder {
            get {
                return ResourceManager.GetString("M_Fixture_Temp_ObjectValidator_UseTableOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート「{0}」が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Fixture_XlsxFile_Read {
            get {
                return ResourceManager.GetString("M_Fixture_XlsxFile_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が設定ファイルの xjc.config セクションにありません。
        ///-------
        ///設定例：
        ///-------
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;xjc.config&quot; type=&quot;System.Configuration.NameValueFileSectionHandler&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///    &lt;xjc.config&gt;
        ///      ...
        ///      &lt;add key=&quot;{0}&quot; value=&quot;設定する値&quot;/&gt;
        ///      ...
        ///    &lt;/xjc.config&gt;
        ///&lt;/configuration&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_Junk_Config_Get {
            get {
                return ResourceManager.GetString("M_Junk_Config_Get", resourceCulture);
            }
        }
    }
}
